---
# tasks file for vscode
- name: Include variables based on OS Family 
  include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Include tasks based on OS Family 
  include_tasks: "vscode-{{ ansible_facts['os_family'] }}.yml"